"""
Built-in question bank for SkillSprint — works without any API key.
Questions organized by: topic keyword → difficulty → list of questions.
"""

import random

QUESTION_BANK = [
    # ===== PYTHON =====
    {"topic": "Python", "difficulty": "beginner", "question_text": "What is the output of `print(type([]))`?", "options": {"A": "<class 'list'>", "B": "<class 'dict'>", "C": "<class 'tuple'>", "D": "<class 'set'>"}, "correct_option": "A", "explanation": "[] creates an empty list, so type([]) returns <class 'list'>."},
    {"topic": "Python", "difficulty": "beginner", "question_text": "Which keyword is used to define a function in Python?", "options": {"A": "func", "B": "define", "C": "def", "D": "function"}, "correct_option": "C", "explanation": "The `def` keyword is used to define functions in Python."},
    {"topic": "Python", "difficulty": "beginner", "question_text": "What does `len('hello')` return?", "options": {"A": "4", "B": "5", "C": "6", "D": "Error"}, "correct_option": "B", "explanation": "The string 'hello' has 5 characters, so len() returns 5."},
    {"topic": "Python", "difficulty": "beginner", "question_text": "Which of these is a mutable data type in Python?", "options": {"A": "str", "B": "tuple", "C": "list", "D": "int"}, "correct_option": "C", "explanation": "Lists are mutable — you can change their contents after creation. Strings, tuples, and ints are immutable."},
    {"topic": "Python", "difficulty": "beginner", "question_text": "What operator is used for exponentiation in Python?", "options": {"A": "^", "B": "**", "C": "//", "D": "%%"}, "correct_option": "B", "explanation": "** is the exponentiation operator. For example, 2**3 = 8. The ^ operator is bitwise XOR."},
    {"topic": "Python", "difficulty": "beginner", "question_text": "How do you create a single-line comment in Python?", "options": {"A": "// comment", "B": "/* comment */", "C": "# comment", "D": "-- comment"}, "correct_option": "C", "explanation": "Python uses # for single-line comments."},
    {"topic": "Python", "difficulty": "beginner", "question_text": "What does the `input()` function return?", "options": {"A": "int", "B": "float", "C": "str", "D": "bool"}, "correct_option": "C", "explanation": "input() always returns a string, even if the user types a number."},
    {"topic": "Python", "difficulty": "beginner", "question_text": "Which of the following is the correct way to create a dictionary?", "options": {"A": "d = []", "B": "d = ()", "C": "d = {}", "D": "d = <>"}, "correct_option": "C", "explanation": "Curly braces {} create an empty dictionary. [] creates a list, () creates a tuple."},

    {"topic": "Python", "difficulty": "intermediate", "question_text": "What is the output of `[x**2 for x in range(5)]`?", "options": {"A": "[1, 4, 9, 16, 25]", "B": "[0, 1, 4, 9, 16]", "C": "[0, 1, 4, 9, 16, 25]", "D": "Error"}, "correct_option": "B", "explanation": "range(5) gives 0,1,2,3,4. Squaring each: 0,1,4,9,16."},
    {"topic": "Python", "difficulty": "intermediate", "question_text": "What does `*args` do in a function definition?", "options": {"A": "Accepts keyword arguments", "B": "Accepts a variable number of positional arguments", "C": "Unpacks a dictionary", "D": "Creates a generator"}, "correct_option": "B", "explanation": "*args allows a function to accept any number of positional arguments as a tuple."},
    {"topic": "Python", "difficulty": "intermediate", "question_text": "What is the difference between `is` and `==`?", "options": {"A": "They are the same", "B": "`is` checks identity, `==` checks equality", "C": "`is` checks equality, `==` checks identity", "D": "`is` only works with numbers"}, "correct_option": "B", "explanation": "`is` checks if two variables point to the same object in memory. `==` checks if their values are equal."},
    {"topic": "Python", "difficulty": "intermediate", "question_text": "What is a lambda function?", "options": {"A": "A named function", "B": "A small anonymous function", "C": "A class method", "D": "A type of loop"}, "correct_option": "B", "explanation": "Lambda functions are small anonymous functions defined with the lambda keyword: lambda x: x+1"},
    {"topic": "Python", "difficulty": "intermediate", "question_text": "What does `enumerate()` do?", "options": {"A": "Sorts a list", "B": "Reverses a list", "C": "Adds a counter to an iterable", "D": "Filters a list"}, "correct_option": "C", "explanation": "enumerate() adds a counter to each item in an iterable, returning (index, value) pairs."},

    {"topic": "Python", "difficulty": "advanced", "question_text": "What is the output of `print(bool('False'))`?", "options": {"A": "False", "B": "True", "C": "Error", "D": "None"}, "correct_option": "B", "explanation": "Any non-empty string is truthy in Python, including the string 'False'."},
    {"topic": "Python", "difficulty": "advanced", "question_text": "What does `@staticmethod` do?", "options": {"A": "Makes a method that can modify the class", "B": "Makes a method that doesn't need self or cls", "C": "Makes a method private", "D": "Makes a method async"}, "correct_option": "B", "explanation": "@staticmethod defines a method that doesn't receive self or cls. It behaves like a regular function that belongs to the class."},
    {"topic": "Python", "difficulty": "advanced", "question_text": "What is a generator in Python?", "options": {"A": "A function that returns a list", "B": "A function that uses yield to return values lazily", "C": "A class that creates objects", "D": "A type of decorator"}, "correct_option": "B", "explanation": "Generators use yield to produce values one at a time, enabling lazy evaluation and memory-efficient iteration."},
    {"topic": "Python", "difficulty": "advanced", "question_text": "What is the GIL in Python?", "options": {"A": "Global Import Lock", "B": "General Iteration Layer", "C": "Global Interpreter Lock", "D": "Generic Interface Library"}, "correct_option": "C", "explanation": "The GIL (Global Interpreter Lock) prevents multiple threads from executing Python bytecode simultaneously in CPython."},
    {"topic": "Python", "difficulty": "advanced", "question_text": "What does `__slots__` do in a class?", "options": {"A": "Defines class methods", "B": "Restricts attributes and saves memory", "C": "Creates private variables", "D": "Enables inheritance"}, "correct_option": "B", "explanation": "__slots__ restricts the attributes an instance can have, avoiding __dict__ creation and saving memory."},

    # ===== JAVASCRIPT =====
    {"topic": "JavaScript", "difficulty": "beginner", "question_text": "Which keyword declares a block-scoped variable?", "options": {"A": "var", "B": "let", "C": "const", "D": "Both B and C"}, "correct_option": "D", "explanation": "Both `let` and `const` are block-scoped. `var` is function-scoped."},
    {"topic": "JavaScript", "difficulty": "beginner", "question_text": "What does `typeof null` return?", "options": {"A": "'null'", "B": "'undefined'", "C": "'object'", "D": "'boolean'"}, "correct_option": "C", "explanation": "This is a well-known JavaScript quirk — typeof null returns 'object' due to a legacy bug."},
    {"topic": "JavaScript", "difficulty": "beginner", "question_text": "How do you write a single-line comment in JavaScript?", "options": {"A": "# comment", "B": "// comment", "C": "-- comment", "D": "/* comment */"}, "correct_option": "B", "explanation": "Single-line comments in JavaScript use //. Multi-line comments use /* */."},
    {"topic": "JavaScript", "difficulty": "beginner", "question_text": "What is the correct way to create an array?", "options": {"A": "let a = (1,2,3)", "B": "let a = [1,2,3]", "C": "let a = {1,2,3}", "D": "let a = <1,2,3>"}, "correct_option": "B", "explanation": "Arrays in JavaScript are created using square brackets []."},
    {"topic": "JavaScript", "difficulty": "beginner", "question_text": "Which method adds an element to the end of an array?", "options": {"A": "append()", "B": "add()", "C": "push()", "D": "insert()"}, "correct_option": "C", "explanation": "The push() method adds one or more elements to the end of an array."},

    {"topic": "JavaScript", "difficulty": "intermediate", "question_text": "What is a closure in JavaScript?", "options": {"A": "A way to close a browser window", "B": "A function that has access to its outer scope's variables", "C": "A method to stop event propagation", "D": "A type of loop"}, "correct_option": "B", "explanation": "A closure is a function that remembers the variables from its outer (enclosing) scope even after the outer function has returned."},
    {"topic": "JavaScript", "difficulty": "intermediate", "question_text": "What does `Promise.all()` do?", "options": {"A": "Runs promises sequentially", "B": "Resolves when ALL promises resolve", "C": "Resolves when ANY promise resolves", "D": "Cancels all promises"}, "correct_option": "B", "explanation": "Promise.all() takes an array of promises and resolves when all of them resolve. It rejects if any one rejects."},
    {"topic": "JavaScript", "difficulty": "intermediate", "question_text": "What is the difference between `==` and `===`?", "options": {"A": "No difference", "B": "`===` is faster", "C": "`==` does type coercion, `===` does not", "D": "`===` only works with strings"}, "correct_option": "C", "explanation": "`==` performs type coercion before comparing, while `===` (strict equality) requires both value and type to match."},
    {"topic": "JavaScript", "difficulty": "intermediate", "question_text": "What does `Array.prototype.map()` return?", "options": {"A": "The original array, modified", "B": "A new array with transformed elements", "C": "undefined", "D": "A boolean"}, "correct_option": "B", "explanation": "map() creates a new array with the results of calling a function on every element. It does not mutate the original."},
    {"topic": "JavaScript", "difficulty": "intermediate", "question_text": "What is event bubbling?", "options": {"A": "Events fire from parent to child", "B": "Events fire from child to parent", "C": "Events fire randomly", "D": "Events fire only on the target"}, "correct_option": "B", "explanation": "Event bubbling means events propagate upward from the target element through its ancestors in the DOM."},

    {"topic": "JavaScript", "difficulty": "advanced", "question_text": "What is the event loop in JavaScript?", "options": {"A": "A for loop that handles events", "B": "A mechanism that handles async callbacks via a task queue", "C": "A library for event handling", "D": "A built-in timer function"}, "correct_option": "B", "explanation": "The event loop continuously checks the call stack and task queue, executing callbacks when the stack is empty."},
    {"topic": "JavaScript", "difficulty": "advanced", "question_text": "What is `WeakMap` used for?", "options": {"A": "Storing primitives", "B": "Key-value pairs where keys are weakly referenced objects", "C": "A faster alternative to Map", "D": "Thread-safe data storage"}, "correct_option": "B", "explanation": "WeakMap holds weak references to object keys, allowing garbage collection if there are no other references."},
    {"topic": "JavaScript", "difficulty": "advanced", "question_text": "What is the Temporal Dead Zone (TDZ)?", "options": {"A": "A timezone handling issue", "B": "The time between entering scope and variable initialization for let/const", "C": "A garbage collection phase", "D": "A performance bottleneck"}, "correct_option": "B", "explanation": "TDZ is the period between entering a block scope and the point where let/const variables are declared. Accessing them here throws ReferenceError."},

    # ===== SQL =====
    {"topic": "SQL", "difficulty": "beginner", "question_text": "Which SQL statement is used to extract data from a database?", "options": {"A": "GET", "B": "EXTRACT", "C": "SELECT", "D": "PULL"}, "correct_option": "C", "explanation": "SELECT is the SQL command used to query and retrieve data from a database."},
    {"topic": "SQL", "difficulty": "beginner", "question_text": "Which clause is used to filter rows?", "options": {"A": "WHERE", "B": "FILTER", "C": "HAVING", "D": "IF"}, "correct_option": "A", "explanation": "WHERE filters rows before grouping. HAVING filters after GROUP BY."},
    {"topic": "SQL", "difficulty": "beginner", "question_text": "What does `SELECT DISTINCT` do?", "options": {"A": "Selects the first row", "B": "Removes duplicate rows from results", "C": "Selects random rows", "D": "Sorts results"}, "correct_option": "B", "explanation": "DISTINCT removes duplicate rows from the result set."},
    {"topic": "SQL", "difficulty": "beginner", "question_text": "Which keyword is used to sort results?", "options": {"A": "SORT BY", "B": "GROUP BY", "C": "ORDER BY", "D": "ARRANGE BY"}, "correct_option": "C", "explanation": "ORDER BY sorts the result set. Default is ASC (ascending)."},
    {"topic": "SQL", "difficulty": "beginner", "question_text": "What is a PRIMARY KEY?", "options": {"A": "The first column in a table", "B": "A column that uniquely identifies each row", "C": "The most important data column", "D": "A password for the database"}, "correct_option": "B", "explanation": "A PRIMARY KEY constraint uniquely identifies each record in a table. It must contain unique, non-null values."},

    {"topic": "SQL", "difficulty": "intermediate", "question_text": "What is the difference between INNER JOIN and LEFT JOIN?", "options": {"A": "No difference", "B": "INNER JOIN returns matching rows only; LEFT JOIN returns all left rows plus matches", "C": "LEFT JOIN is faster", "D": "INNER JOIN includes NULLs"}, "correct_option": "B", "explanation": "INNER JOIN returns only rows with matches in both tables. LEFT JOIN returns all rows from the left table, with NULLs where there's no match."},
    {"topic": "SQL", "difficulty": "intermediate", "question_text": "What does `GROUP BY` do?", "options": {"A": "Sorts data", "B": "Groups rows that have the same values for aggregation", "C": "Filters rows", "D": "Joins tables"}, "correct_option": "B", "explanation": "GROUP BY groups rows with the same values into summary rows, often used with aggregate functions like COUNT, SUM, AVG."},
    {"topic": "SQL", "difficulty": "intermediate", "question_text": "What is a subquery?", "options": {"A": "A query inside another query", "B": "A backup query", "C": "A query that runs in parallel", "D": "A stored procedure"}, "correct_option": "A", "explanation": "A subquery is a query nested inside another SQL statement, often in WHERE, FROM, or SELECT clauses."},
    {"topic": "SQL", "difficulty": "intermediate", "question_text": "What does `COALESCE(a, b, c)` return?", "options": {"A": "Always returns a", "B": "Returns the first non-NULL value", "C": "Returns the sum of a, b, c", "D": "Returns the average"}, "correct_option": "B", "explanation": "COALESCE returns the first non-NULL argument. If all are NULL, it returns NULL."},

    {"topic": "SQL", "difficulty": "advanced", "question_text": "What is a window function?", "options": {"A": "A function that opens database connections", "B": "A function that performs calculations across a set of rows related to the current row", "C": "A GUI function", "D": "A backup function"}, "correct_option": "B", "explanation": "Window functions perform calculations over a 'window' of rows (defined by OVER clause) without collapsing them into a single output row."},
    {"topic": "SQL", "difficulty": "advanced", "question_text": "What is database normalization?", "options": {"A": "Making all data uppercase", "B": "Organizing data to reduce redundancy and dependency", "C": "Compressing the database", "D": "Backing up data"}, "correct_option": "B", "explanation": "Normalization is the process of structuring tables to minimize redundancy and ensure data integrity through normal forms (1NF, 2NF, 3NF)."},
    {"topic": "SQL", "difficulty": "advanced", "question_text": "What does `EXPLAIN` do?", "options": {"A": "Shows the table schema", "B": "Shows the query execution plan", "C": "Comments the query", "D": "Deletes the query log"}, "correct_option": "B", "explanation": "EXPLAIN shows how the database engine will execute a query — which indexes it uses, join order, estimated rows, etc."},

    # ===== CLOUD =====
    {"topic": "Cloud", "difficulty": "beginner", "question_text": "What does EC2 stand for?", "options": {"A": "Elastic Cloud Compute", "B": "Elastic Compute Cloud", "C": "Easy Cloud Computing", "D": "Enterprise Compute Cloud"}, "correct_option": "B", "explanation": "EC2 stands for Elastic Compute Cloud — Amazon's scalable virtual server service."},
    {"topic": "Cloud", "difficulty": "beginner", "question_text": "What is S3 used for?", "options": {"A": "Running code", "B": "Object storage", "C": "Email service", "D": "DNS management"}, "correct_option": "B", "explanation": "Amazon S3 (Simple Storage Service) is an object storage service for storing and retrieving any amount of data."},
    {"topic": "Cloud", "difficulty": "beginner", "question_text": "What is IAM?", "options": {"A": "Internet Access Module", "B": "Identity and Access Management", "C": "Intelligent API Manager", "D": "Internal Application Monitor"}, "correct_option": "B", "explanation": "IAM (Identity and Access Management) controls who can access what in your AWS account."},
    {"topic": "Cloud", "difficulty": "beginner", "question_text": "What is a VPC?", "options": {"A": "Virtual Private Cloud", "B": "Virtual Public Container", "C": "Variable Processing Core", "D": "Visual Programming Console"}, "correct_option": "A", "explanation": "A VPC (Virtual Private Cloud) is a logically isolated section of the cloud where you can launch resources."},
    {"topic": "Cloud", "difficulty": "beginner", "question_text": "What type of service is AWS Lambda?", "options": {"A": "Virtual machine", "B": "Serverless compute", "C": "Database", "D": "CDN"}, "correct_option": "B", "explanation": "Lambda is a serverless compute service — you run code without provisioning or managing servers."},

    {"topic": "Cloud", "difficulty": "intermediate", "question_text": "What is auto-scaling?", "options": {"A": "Automatically backing up data", "B": "Automatically adjusting compute capacity based on demand", "C": "Automatically updating software", "D": "Automatically encrypting data"}, "correct_option": "B", "explanation": "Auto-scaling automatically increases or decreases the number of instances based on traffic and demand."},
    {"topic": "Cloud", "difficulty": "intermediate", "question_text": "What is CloudFormation?", "options": {"A": "A weather prediction service", "B": "Infrastructure as Code (IaC) service for AWS", "C": "A cloud monitoring tool", "D": "A CI/CD pipeline"}, "correct_option": "B", "explanation": "CloudFormation is AWS's IaC service that lets you define and provision infrastructure using templates."},
    {"topic": "Cloud", "difficulty": "intermediate", "question_text": "What is the difference between RDS and DynamoDB?", "options": {"A": "No difference", "B": "RDS is relational, DynamoDB is NoSQL", "C": "DynamoDB is relational, RDS is NoSQL", "D": "Both are NoSQL"}, "correct_option": "B", "explanation": "RDS is a managed relational database service (MySQL, PostgreSQL, etc.). DynamoDB is a managed NoSQL key-value/document database."},

    {"topic": "Cloud", "difficulty": "advanced", "question_text": "What is a CDK in AWS?", "options": {"A": "Cloud Development Kit — define infrastructure in code using languages like Python/JS", "B": "Cloud Deployment Key", "C": "Content Delivery Kit", "D": "Container Development Kit"}, "correct_option": "A", "explanation": "AWS CDK (Cloud Development Kit) lets you define cloud infrastructure using familiar programming languages like Python, TypeScript, or Java."},
    {"topic": "Cloud", "difficulty": "advanced", "question_text": "What is the Shared Responsibility Model?", "options": {"A": "AWS shares costs with customers", "B": "AWS secures the cloud infrastructure; customers secure data and access", "C": "Customers manage all security", "D": "AWS manages all security"}, "correct_option": "B", "explanation": "In the Shared Responsibility Model, AWS is responsible for security OF the cloud; customers are responsible for security IN the cloud (data, IAM, configs)."},

    # ===== DSA =====
    {"topic": "DSA", "difficulty": "beginner", "question_text": "What is the time complexity of accessing an element in an array by index?", "options": {"A": "O(n)", "B": "O(log n)", "C": "O(1)", "D": "O(n²)"}, "correct_option": "C", "explanation": "Array access by index is O(1) — constant time — because arrays store elements in contiguous memory."},
    {"topic": "DSA", "difficulty": "beginner", "question_text": "What data structure uses FIFO (First In, First Out)?", "options": {"A": "Stack", "B": "Queue", "C": "Array", "D": "Tree"}, "correct_option": "B", "explanation": "A Queue follows FIFO — the first element added is the first one removed. A Stack uses LIFO."},
    {"topic": "DSA", "difficulty": "beginner", "question_text": "What does LIFO stand for?", "options": {"A": "Last In, First Out", "B": "Last In, Fast Out", "C": "List In, First Out", "D": "Low Input, Fast Output"}, "correct_option": "A", "explanation": "LIFO (Last In, First Out) is the principle used by Stacks. The last element pushed is the first one popped."},
    {"topic": "DSA", "difficulty": "beginner", "question_text": "What is the time complexity of linear search?", "options": {"A": "O(1)", "B": "O(log n)", "C": "O(n)", "D": "O(n²)"}, "correct_option": "C", "explanation": "Linear search checks each element one by one, so in the worst case it checks all n elements: O(n)."},
    {"topic": "DSA", "difficulty": "beginner", "question_text": "Which sorting algorithm has the best average time complexity?", "options": {"A": "Bubble Sort - O(n²)", "B": "Merge Sort - O(n log n)", "C": "Selection Sort - O(n²)", "D": "Insertion Sort - O(n²)"}, "correct_option": "B", "explanation": "Merge Sort has O(n log n) average and worst-case complexity, making it more efficient than quadratic sorts."},

    {"topic": "DSA", "difficulty": "intermediate", "question_text": "What is a hash collision?", "options": {"A": "Two keys produce the same hash value", "B": "A hash function that is too slow", "C": "Deleting from a hash table", "D": "Hashing a null value"}, "correct_option": "A", "explanation": "A collision occurs when two different keys produce the same hash value. This is handled via chaining or open addressing."},
    {"topic": "DSA", "difficulty": "intermediate", "question_text": "What is the height of a balanced binary tree with n nodes?", "options": {"A": "O(n)", "B": "O(log n)", "C": "O(n²)", "D": "O(1)"}, "correct_option": "B", "explanation": "A balanced binary tree has height O(log n), which enables efficient search, insert, and delete operations."},
    {"topic": "DSA", "difficulty": "intermediate", "question_text": "What is BFS?", "options": {"A": "Binary File Search", "B": "Breadth-First Search — explores neighbors level by level", "C": "Best-First Sort", "D": "Block-Free Sorting"}, "correct_option": "B", "explanation": "BFS (Breadth-First Search) explores a graph level by level using a queue. It finds the shortest path in unweighted graphs."},
    {"topic": "DSA", "difficulty": "intermediate", "question_text": "What is the time complexity of binary search?", "options": {"A": "O(n)", "B": "O(n²)", "C": "O(log n)", "D": "O(1)"}, "correct_option": "C", "explanation": "Binary search halves the search space each step, giving O(log n) time complexity on sorted arrays."},

    {"topic": "DSA", "difficulty": "advanced", "question_text": "What is dynamic programming?", "options": {"A": "Programming with dynamic types", "B": "Breaking problems into overlapping subproblems and storing results", "C": "Using dynamic memory allocation", "D": "Creating dynamic websites"}, "correct_option": "B", "explanation": "DP solves problems by breaking them into overlapping subproblems, storing results to avoid recomputation (memoization/tabulation)."},
    {"topic": "DSA", "difficulty": "advanced", "question_text": "What is the time complexity of Dijkstra's algorithm with a min-heap?", "options": {"A": "O(V²)", "B": "O(V + E)", "C": "O((V + E) log V)", "D": "O(E log E)"}, "correct_option": "C", "explanation": "With a binary min-heap, Dijkstra's runs in O((V + E) log V), where V is vertices and E is edges."},
    {"topic": "DSA", "difficulty": "advanced", "question_text": "What is an AVL tree?", "options": {"A": "A type of hash table", "B": "A self-balancing binary search tree where heights of subtrees differ by at most 1", "C": "A graph traversal algorithm", "D": "A sorting algorithm"}, "correct_option": "B", "explanation": "AVL trees maintain balance by ensuring the height difference (balance factor) between left and right subtrees is at most 1, using rotations."},

    # ===== REACT =====
    {"topic": "React", "difficulty": "beginner", "question_text": "What is JSX?", "options": {"A": "A JavaScript database", "B": "A syntax extension that looks like HTML in JavaScript", "C": "A CSS framework", "D": "A testing library"}, "correct_option": "B", "explanation": "JSX is a syntax extension for JavaScript that lets you write HTML-like code in your React components."},
    {"topic": "React", "difficulty": "beginner", "question_text": "What hook is used to manage state in a functional component?", "options": {"A": "useEffect", "B": "useRef", "C": "useState", "D": "useContext"}, "correct_option": "C", "explanation": "useState is the React hook for adding state to functional components. It returns [value, setter]."},
    {"topic": "React", "difficulty": "beginner", "question_text": "What is a component in React?", "options": {"A": "A database table", "B": "A reusable piece of UI", "C": "A CSS class", "D": "An API endpoint"}, "correct_option": "B", "explanation": "Components are the building blocks of React — reusable, independent pieces of UI that manage their own state."},
    {"topic": "React", "difficulty": "beginner", "question_text": "How do you pass data from parent to child in React?", "options": {"A": "Using state", "B": "Using props", "C": "Using context only", "D": "Using localStorage"}, "correct_option": "B", "explanation": "Props (short for properties) are the primary way to pass data from a parent component to a child component."},
    {"topic": "React", "difficulty": "beginner", "question_text": "What does the `key` prop do in a list?", "options": {"A": "Styles the element", "B": "Helps React identify which items changed, added, or removed", "C": "Sets the element's ID", "D": "Encrypts the element"}, "correct_option": "B", "explanation": "The key prop helps React efficiently update the DOM by tracking which list items have changed."},

    {"topic": "React", "difficulty": "intermediate", "question_text": "When does `useEffect` run by default?", "options": {"A": "Only on mount", "B": "After every render", "C": "Only when props change", "D": "Only on unmount"}, "correct_option": "B", "explanation": "Without a dependency array, useEffect runs after every render. With [], it runs only on mount. With [deps], it runs when deps change."},
    {"topic": "React", "difficulty": "intermediate", "question_text": "What is the Context API used for?", "options": {"A": "Making API calls", "B": "Passing data deeply without prop drilling", "C": "Styling components", "D": "Routing"}, "correct_option": "B", "explanation": "Context API provides a way to pass data through the component tree without manually passing props at every level."},
    {"topic": "React", "difficulty": "intermediate", "question_text": "What is React.memo?", "options": {"A": "A state management tool", "B": "A HOC that memoizes a component to prevent unnecessary re-renders", "C": "A routing library", "D": "A debugging tool"}, "correct_option": "B", "explanation": "React.memo is a higher-order component that skips re-rendering if the props haven't changed."},
    {"topic": "React", "difficulty": "intermediate", "question_text": "What does `useRef` return?", "options": {"A": "A state variable", "B": "A mutable ref object with a `.current` property", "C": "A callback function", "D": "A context value"}, "correct_option": "B", "explanation": "useRef returns {current: value}. The .current property persists across renders without causing re-renders."},

    {"topic": "React", "difficulty": "advanced", "question_text": "What is React's reconciliation algorithm?", "options": {"A": "A styling engine", "B": "The diffing algorithm that compares virtual DOM trees to minimize real DOM updates", "C": "A state management pattern", "D": "An error handling mechanism"}, "correct_option": "B", "explanation": "Reconciliation is React's process of comparing the previous and next virtual DOM trees to determine the minimal set of DOM operations needed."},
    {"topic": "React", "difficulty": "advanced", "question_text": "What is a custom hook?", "options": {"A": "A built-in React hook", "B": "A reusable function that uses React hooks and starts with 'use'", "C": "A third-party library", "D": "A class method"}, "correct_option": "B", "explanation": "Custom hooks are functions starting with 'use' that encapsulate reusable logic using React hooks."},
    {"topic": "React", "difficulty": "advanced", "question_text": "What is Concurrent Mode in React?", "options": {"A": "Running React on multiple servers", "B": "A set of features that help React render without blocking the main thread", "C": "Using multiple state managers", "D": "Server-side rendering"}, "correct_option": "B", "explanation": "Concurrent Mode lets React pause, resume, and prioritize rendering work, keeping the app responsive during heavy updates."},
]


def get_builtin_questions(topic_query, difficulty, count=5):
    """
    Search the built-in bank by topic keyword and difficulty.
    topic_query can be 'Python', 'Python - OOP', 'JavaScript - Closures', etc.
    We match against the topic field and optionally the question text.
    """
    topic_key = topic_query.split(' - ')[0].strip() if ' - ' in topic_query else topic_query.strip()
    subtopic = topic_query.split(' - ')[1].strip().lower() if ' - ' in topic_query else None

    # Filter by topic and difficulty
    pool = [q for q in QUESTION_BANK if q['topic'].lower() == topic_key.lower() and q['difficulty'] == difficulty]

    # If subtopic specified, prefer questions matching it in question_text
    if subtopic and pool:
        subtopic_matches = [q for q in pool if subtopic in q['question_text'].lower() or subtopic in q.get('explanation', '').lower()]
        if len(subtopic_matches) >= count:
            pool = subtopic_matches

    random.shuffle(pool)
    return pool[:count]
